# Generated by Django 3.1.5 on 2021-01-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='from2',
            name='number2',
        ),
    ]
